### ISSUE TITLE
Chameleon Twist

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#199] opened 2020-06-30 02:14 UTC
# Game summary
- Game name: Chameleon Twist
- Game version: v1.1, USA

# Daedalus X64 summary
- Version: v0.4

# Issues
None that I've noticed. No visual glitches or slowdown to be seen on Stage 1. All text looks good. Pause menu looks good. Audio seems fine. Very enjoyable game on the Vita.

# Screenshots
![](https://?)

# Recommended labels

- A? Playable
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-06-30 08:02
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/119

**Closed by Rinnegatamante** 2020-06-30 08:02 UTC
