### ISSUE TITLE
Extreme-G XG2

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#279] opened 2020-07-27 18:21 UTC
# Game summary
- Game name: Extreme-G XG2
- Game version: USA

# Daedalus X64 summary
- Version: v0.4 nightly

# Issues

None

# Screenshots
![](https://?)

# Recommended labels

Playable
- A?
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-07-27 19:16
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/126

**Closed by Rinnegatamante** 2020-07-27 19:16 UTC
Labels: Playable
