### ISSUE TITLE
Star Fox 64

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#204] opened 2020-06-30 04:35 UTC
# Game summary
- Game name: Star Fox 64
- Game version: USA

# Daedalus X64 summary
- Version: v0.4

# Issues
Minor performance issue on the Lylat overview (stage selection). Played all the way through Corneria, Asteroid Field, Fortuna, and Solar. I only recall having moderate performance issues on Fortuna. The other stages ran very well with rare minor dips. The Forever Train stage (the beginning of it, at least) runs similarly to Fortuna. Overall, the game is very enjoyable.

# Screenshots
![](https://?)

# Recommended labels

- A? Playable
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-06-30 08:01
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/63

**Closed by Rinnegatamante** 2020-06-30 08:01 UTC
