### ISSUE TITLE
Dr. Mario 64

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#193] opened 2020-05-27 06:46 UTC
# Game summary
- Game name: Dr. Mario 64
- Game version: USA

# Daedalus X64 summary
- Version: v0.3 nightly

# Issues

Once in game, the background textures are very corrupted so can't really play

# Screenshots
![](https://?)

# Recommended labels

- A?
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-07-03 15:14
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/175

**Closed by Rinnegatamante** 2020-07-03 15:14 UTC
Labels: Ingame (low)
