### ISSUE TITLE
Blast Corps

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#200] opened 2020-06-30 02:26 UTC
# Game summary
- Game name: Blast Corps
- Game version: v1.0, USA

# Daedalus X64 summary
- Version: v0.4

# Issues
Crashes after the Rareware logo.

# Screenshots
![](https://?)

# Recommended labels

- A? Crash
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-06-30 08:02
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/38

**Closed by Rinnegatamante** 2020-06-30 08:02 UTC
