### ISSUE TITLE
Army Men: Sarge's Heroes 2

### ISSUE THREAD

**Issue by Sarkie** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#177] opened 2020-05-20 08:08 UTC
# Game summary
- Game name: Army Men: Sarge's Heroes
- Game version: 1.0 E/U

# Daedalus X64 summary
- Version: v0.3 2020/05/20 Nightly

# Issues
Almost perfect, everything works, just game play is slow and none of the options will speed it up.

**Comment by Sarkie** [comment] 2020-05-20 08:09
Seems to only use 1 core during game play a lot of the time.

**Comment by Rinnegatamante** [comment] 2020-05-20 08:40
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/162

**Closed by Rinnegatamante** 2020-05-20 08:40 UTC

**Comment by Sarkie** [comment] 2020-05-20 09:48
this is the sequel.

**Comment by Rinnegatamante** [comment] 2020-05-20 10:38
Army Men: Sarge's Heroes 2 is not the sequel of Army Men: Sarge's Heroes 2.

**Comment by Sarkie** [comment] 2020-05-20 12:54
Ha! Sorry I read what I wanted to read. It just wasn't showing in the app with a label
