### ISSUE TITLE
Space Station Silicon Valley

### ISSUE THREAD

**Issue by Jodeth** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#202] opened 2020-06-30 03:25 UTC
# Game summary
- Game name: Space Station Silicon Valley
- Game version: USA

# Daedalus X64 summary
- Version: v0.4

# Issues
Minor slowdown in the intro movie (Not the news channel). Zone Select screen lacks visuals on the selection wheel and there's a grey flicker every few seconds along with white noise (I'm not sure if this was actually programmed in the game or not).
Performance overall is very good. Solid framerate on the beginning stage with the crashed rocketship. Second stage has a little slowdown at the beginning, but eventually smooths itself out and runs at full speed almost everywhere. Water texture is missing. Audio is slightly crackly.

# Screenshots
![](https://?)

# Recommended labels

- A? Playable
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-06-30 08:03
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/195

**Closed by Rinnegatamante** 2020-06-30 08:03 UTC
