### ISSUE TITLE
Lego Racers 

### ISSUE THREAD

**Issue by YTJaquanButler** [Rinnegatamante/DaedalusX64-vitaGL-Compatibility#134] opened 2020-05-09 20:29 UTC
#18 
- Lego Racers
- USA Version 

# Daedalus X64 summary
-the menu is all zoomed in so unless you played it before it will be hard to choose what mode but after i got into a race im getting a good 39-40fps
but the menu runs perfectly just the zoom issue

Version v0.2

# Issues

# Screenshots
![](https://?)

# Recommended labels
- A?Playable
- B?
- C?

**Comment by Rinnegatamante** [comment] 2020-05-09 20:52
Duplicate of https://github.com/Rinnegatamante/DaedalusX64-vitaGL-Compatibility/issues/18

**Closed by Rinnegatamante** 2020-05-09 20:52 UTC
